### ISSUE TITLE
Q3

### ISSUE THREAD

**Issue by Jatin-1956** [01-DC/Computer_Assignment#1]
When running the program Q3_A1.c

 ` printf("Give input number: ");` should be included outside of the while loop and it's also worth mentioning users to input the numbers after a space rather than using new line (pressing enter key) otherwise the output will be just a repetition.

[https://github.com/01-DC/Computer_Assignment/blob/main/Q3_A1.c](url)

**Comment by 01-DC** [comment]
I reviewed your code and it solves this issue. This issue is now closed.
